// Code generated by "stringer -type=InterpretResult"; DO NOT EDIT.

package vm

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[INTERPRET_OK-0]
	_ = x[INTERPRET_COMPILE_ERROR-1]
	_ = x[INTERPRET_RUNTIME_ERROR-2]
}

const _InterpretResult_name = "INTERPRET_OKINTERPRET_COMPILE_ERRORINTERPRET_RUNTIME_ERROR"

var _InterpretResult_index = [...]uint8{0, 12, 35, 58}

func (i InterpretResult) String() string {
	if i >= InterpretResult(len(_InterpretResult_index)-1) {
		return "InterpretResult(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _InterpretResult_name[_InterpretResult_index[i]:_InterpretResult_index[i+1]]
}
